app_token:
  class: sfPropelRouteCollection
  options:
    model:                AppToken
    module:               appTokens
    prefix_path:          /appTokens
    column:               id
    with_wildcard_routes: true

photo_show:
  url: /:app_token/show/photo/:event_key/:photo_id
  param: { module: photos, action: showPhoto, app_token: app }

photo_user:
  url: /:app_token/user/photos
  param: { module: photos, action: getUserPhotos, app_token: app }

photo_event:
  url: /:app_token/event/photos/:key
  param: { module: photos, action: getEventPhotos, app_token: app }

photo_upload:
  url: /:app_token/event/upload/:key
  param: { module: photos, action: uploadPhoto, app_token: app }

#------------------------------------------------------------------#

event_program_update:
  url: /:app_token/event/program/update
  param: { module: events, action: saveProgram, app_token: app }

event_create:
  url: /:app_token/event/create
  param: { module: events, action: save, app_token: app }
  
event_edit:
  url: /:app_token/event/save
  param: { module: events, action: save, app_token: app }

event_invite:
  url: /:app_token/event/invite/:key
  param: { module: events, action: invite, app_token: app }
  
event_join_user_get:
  url: /:app_token/event/web/join/:key
  param: { module: default, action: webJoin, app_token: app }

event_unjoin_user:
  url: /:app_token/event/remove/:key/:who
  param: { module: events, action: unjoin, app_token: app }

event_join_user:
  url: /:app_token/event/join/:key
  param: { module: events, action: join, app_token: app }

event_list_user:
  url: /:app_token/event/participation/:who
  param: { module: events, action: listUsers, app_token: app }

event_list_admin:
  url: /:app_token/event/list/admin/:who
  param: { module: events, action: listAdmins, app_token: app }

event_info:
  url: /:app_token/event/info/:key
  param: { module: events, action: getInfo, app_token: app }


#-------------------------------------------------------------------#
create_user:
  url: /:app_token/user/create
  param: { module: users, action: createUser, app_token: app }
info_user:
  url: /:app_token/user/info/:who
  param: { module: users, action: getInfo, app_token: app }
logout_user:
  url: /:app_token/user/logout
  param: { module: users, action: logOutUser, app_token: app }
login_user:
  url: /:app_token/user/validate/:username
  param: { module: users, action: logInUser, app_token: app }
check_token:
  url: /:app_token/user/token/check/:username
  param: { module: users, action: checkToken, app_token: app }
  
homepage:
  url:   /
  param: { module: default, action: index }
  

