eventus_main:
    resource: "@EventusMainBundle/Controller/"
    type:     annotation
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

users:
    type: rest
    resource:   Eventus\MainBundle\Controller\UsersController
    