<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/09/24 17:12:46
$this->security = array (
  'loginuser' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
