<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/09/09 20:04:33

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=eventus;host=localhost',
  'username' => 'root',
  'password' => 'gorilafeliz',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
