<?php

/**
 * Skeleton subclass for performing query and update operations on the 'eventos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Aug  5 15:38:17 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EventPeer extends BaseEventPeer {

    public static function retrieveByKey($key) {
        $c = new Criteria();
        $c->add(self::KEY, $key);
        $c->add(self::ACTIVE, 1);

        return self::doSelectOne($c);
    }

    public static function retrieveByAdmin(sfGuardUser $user, $active = 1) {
        $c = new Criteria();
        $c->add(self::ADMIN_ID, $user->getId());
        $c->add(self::ACTIVE, $active);

        return self::doSelect($c);
    }

    public static function retrieveUsersEvent(sfGuardUser $user, $active = 1) {
        $c = new Criteria();
        $c->add(ParticipationPeer::USER_ID, $user->getId());
        $c->add(ParticipationPeer::ACTIVE, $active);

        $participations = ParticipationPeer::doSelect($c);

        $ids = array();
        foreach ($participations as $p) {
            $ids[] = $p->getEventId();
        }

        $c = new Criteria();
        $c->add(self::ID, $ids, Criteria::IN);
        $c->add(self::ACTIVE, 1);
        
        return self::doSelect($c);
    }

}

// EventPeer
