<?php

/**
 * Skeleton subclass for representing a row from the 'users_event' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Aug  5 15:59:10 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Participation extends BaseParticipation {

    public function create(sfGuardUser $user, Event $event, $save = 0) {

        $this->setUserId($user->getId());
        $this->setEventId($event->getId());
        $this->setJoinedAt(time());
        if ($save)
            $this->save();
    }

    private function getUser(){
        return sfGuardUserPeer::retrieveByPK($this->getUserId());
    }
    public function expose() {
        //return get_object_vars($this);
        return array('username'=>$this->getUser()->getUsername(), 'eventname' => $this->getEvent()->getName(),'joined_at'=>$this->getJoinedAt());
    }

    public static function checkJoined(sfGuardUser $user, Event $event) {
        return ParticipationPeer::retrieveByPk($user->getId(), $event->getId()) != null;
    }

    public static function exposeParticipantList($list) {
        # $list<$user> typeof sfGuardUser
        $retval = array();
        foreach ($list as $user) {
            $retval[] = $user->getUsername();
        }
        return $retval;
    }

}

// Participation
