<?php


/**
 * Skeleton subclass for performing query and update operations on the 'photos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 22 16:45:29 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PhotoPeer extends BasePhotoPeer {
    
    public static function retrieveByEventId($id){
        $c = new Criteria();
        $c->add(self::EVENT_ID, $id);
        $c->add(self::DELETED,0);
        return self::doSelect($c);
    }
    
    public static function retrieveByUserId($id){
        $c = new Criteria();
        $c->add(self::USER_ID, $id);
        $c->add(self::DELETED,0);
        return self::doSelect($c);
    }

} // PhotoPeer
