<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_user_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jul 23 14:20:09 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class sfGuardUserProfilePeer extends BasesfGuardUserProfilePeer {

    public static function retrieveUserByEmail($email){
        $c = new Criteria();
        $c->add(self::EMAIL,$email);
        $profile = self::doSelectOne($c);
        if($profile == null) return null;
        else return sfGuardUserPeer::retrieveByPK($profile->getUserId());
    }
    
} // sfGuardUserProfilePeer
