<?php

/**
 * Skeleton subclass for representing a row from the 'sf_guard_user_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jul 23 14:20:09 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class sfGuardUserProfile extends BasesfGuardUserProfile {

    public function expose() {
        //return get_object_vars($this);
        return array('firstname'=> $this->getFirstName(),'lastname'=>$this->getLastname(),'email'=>$this->getEmail());
    }

    public function toJSON(){
        return json_encode($this->expose());
    }
    
}

// sfGuardUserProfile
