<?php

/**
 * Skeleton subclass for representing a row from the 'tokens' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Jul 31 19:07:17 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Token extends BaseToken {

    /**
     * Initializes internal state of Token object.
     * @see        parent::__construct()
     */
    public function __construct() {
        // Make sure that parent constructor is always invoked, since that
        // is where any default values for this object are set.
        parent::__construct();
    }

    public static function createTokenForUser($user) {
        $token = new Token();
        $token->setToken($user->getSalt());
        $token->setUserId($user->getId());
        $token->setActive(1);
        $token->setCreatedAt(time());
        $token->save();

        return $token;
    }

    public static function check($user, $token) {
        
        if($user == null || ! $user instanceof sfGuardUser) return false;

        $c = new Criteria();
        $c->add(TokenPeer::USER_ID, $user->getId());
        $c->add(TokenPeer::TOKEN, $token);
        $c->add(TokenPeer::ACTIVE, 1);

        $t = TokenPeer::doSelect($c);

        return $t != null;
    }

}

// Token