<?php

/**
 * Skeleton subclass for representing a row from the 'tokens' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jul 23 18:14:21 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Tokens extends BaseTokens {

    public static function createTokenForUser($user) {
        $token = new Tokens();
        $token->setToken($user->getSalt());
        $token->setUserId($user->getId());
        $token->setCreatedAt(time());
        $token->save();
        
        return $token;
    }

    public static function check(sfGuardUser $user, $token) {

        $c = new Criteria();
        $c->add(TokensPeer::USER_ID, $user->getId());
        $c->add(TokensPeer::TOKEN, $token);
        $c->add(TokensPeer::ACTIVE, 1);

        $t = TokensPeer::doSelect($c);

        return $t != null;
    }

}

// Tokens
