# CreateUser: POST parameters
# All variables from a user via POST.
create_user:
  url: /:app_token/user/create
  param: { module: users, action: createUser, app_token: app }

# Get User Info: POST and Route parameters
#  username -> route & post
#  token -> post
info_user:
  url: /:app_token/user/info/:username
  param: { module: users, action: getInfo, app_token: app }

# Validate Users: POST and Route parameters
#  username -> route & post
#  password -> post
validate_user:
  url: /:app_token/user/validate/:username
  param: { module: users, action: validateUser, app_token: app }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }
  

